### ISSUE TITLE
🐞 错误报告 ：启动报错，小白求救

### ISSUE THREAD

**Issue by hbzengcan** [JimmyLv/BibiGPT#131]
# 错误报告 🐞

执行构建时npm run dev报错，请教一下这是为啥

## 错误描述 🤔

拉取完代码之后，执行了npm install，然后使用npm run dev就报错了，本人对于前台比较小白，希望得到帮助，感谢！！！

另外，如果您在解决问题时已经查看过其他 GitHub Issue，请务必在文本中说明并引用相关信息。

## 附加信息 📝
`SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\visual_space\BibiGPT\node_modules\next\dist\telemetry\post-payload.js:17:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bibi-gpt@2.22.0 dev:  next dev
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bibi-gpt@2.22.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

感谢您的反馈！🙏

**Comment by JimmyLv** [comment]
需要按照 ./example.env 文件设置环境变量哦。

现在急用的话， [BibiGPT.co](https://b.jimmylv.cn) 网站上是支持使用自己的 apikey 的啦

**Comment by Nancycometoplay** [comment]
应该是node版本太低了 升到15以上
