### ISSUE TITLE
🐞 错误报告 本地启动报错

### ISSUE THREAD

**Issue by AmosWong1998** [JimmyLv/BibiGPT#132]
# 错误报告 🐞

## 错误描述 🤔
已经在项目的.example.env文件中配置了NEXT_PUBLIC_SUPABASE_URL和NEXT_PUBLIC_SUPABASE_ANON_KEY属性，但是启动还是报错，报错的大意是没有配置这两个属性：
<img width="1042" alt="image" src="https://github.com/JimmyLv/BibiGPT/assets/41744494/3cc9e274-6dc1-4d66-aef3-5ce6ba1bd249">

<img width="1152" alt="image" src="https://github.com/JimmyLv/BibiGPT/assets/41744494/403e6ed5-12e1-468f-9b2d-0643bf97945a">

**Comment by UNICKCHENG** [comment]
@AmosWong1998 把 `.example.env` 文件名改成 `.env`

**Comment by AmosWong1998** [comment]
> @AmosWong1998 把 `.example.env` 文件名改成 `.env`

感谢大哥这个问题已经解决了，但是有个新的报错：
Error [NextFontError]: Failed to fetch `Inter` from Google Fonts.
    at nextFontError (D:\Work\BibiGPT\node_modules\@next\font\dist\utils.js:55:17)
    at downloadGoogleFonts (D:\Work\BibiGPT\node_modules\@next\font\dist\google\loader.js:87:39)
    at D:\Work\BibiGPT\node_modules\next\dist\build\webpack\loaders\next-font-loader\index.js:52:99
    at async Span.traceAsyncFn (D:\Work\BibiGPT\node_modules\next\dist\trace\trace.js:79:20)
error - Failed to download `Inter` from Google Fonts. Using fallback font instead.
Error [NextFontError]: Failed to fetch `Poppins` from Google Fonts.
    at nextFontError (D:\Work\BibiGPT\node_modules\@next\font\dist\utils.js:55:17)
    at downloadGoogleFonts (D:\Work\BibiGPT\node_modules\@next\font\dist\google\loader.js:87:39)
    at D:\Work\BibiGPT\node_modules\next\dist\build\webpack\loaders\next-font-loader\index.js:52:99
    at async Span.traceAsyncFn (D:\Work\BibiGPT\node_modules\next\dist\trace\trace.js:79:20)
error - Failed to download `Poppins` from Google Fonts. Using fallback font instead.
error - ./node_modules/@supabase/auth-helpers-nextjs/dist/index.js:207:14
Module not found: Can't resolve 'console'

Import trace for requested module:
./pages/_app.tsx

https://nextjs.org/docs/messages/module-not-found
wait  - compiling...
error - ./node_modules/@supabase/auth-helpers-nextjs/dist/index.js:207:14
Module not found: Can't resolve 'console'

Import trace for requested module:
./pages/_app.tsx

https://nextjs.org/docs/messages/module-not-found
wait  - compiling /_error (client and server)...
Error [NextFontError]: Failed to fetch `Inter` from Google Fonts.
    at nextFontError (D:\Work\BibiGPT\node_modules\@next\font\dist\utils.js:55:17)
    at downloadGoogleFonts (D:\Work\BibiGPT\node_modules\@next\font\dist\google\loader.js:87:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async D:\Work\BibiGPT\node_modules\next\dist\build\webpack\loaders\next-font-loader\index.js:52:93
    at async Span.traceAsyncFn (D:\Work\BibiGPT\node_modules\next\dist\trace\trace.js:79:20)
error - Failed to download `Inter` from Google Fonts. Using fallback font instead.
Error [NextFontError]: Failed to fetch `Poppins` from Google Fonts.
    at nextFontError (D:\Work\BibiGPT\node_modules\@next\font\dist\utils.js:55:17)
    at downloadGoogleFonts (D:\Work\BibiGPT\node_modules\@next\font\dist\google\loader.js:87:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async D:\Work\BibiGPT\node_modules\next\dist\build\webpack\loaders\next-font-loader\index.js:52:93
    at async Span.traceAsyncFn (D:\Work\BibiGPT\node_modules\next\dist\trace\trace.js:79:20)
error - Failed to download `Poppins` from Google Fonts. Using fallback font instead.
error - ./node_modules/@supabase/auth-helpers-nextjs/dist/index.js:207:14
Module not found: Can't resolve 'console'

Import trace for requested module:
./pages/_app.tsx

https://nextjs.org/docs/messages/module-not-found


本机的node版本是18.16.1

**Comment by UNICKCHENG** [comment]
@AmosWong1998  网络问题。如果只是部署的话，可以直接使用 vercel，如果想运行一遍代码，可以使用 codespace
![image](https://github.com/JimmyLv/BibiGPT/assets/32270702/9ddc79ca-22f2-4c7f-816f-563a9f724dd5)
