### ISSUE TITLE
🐞 错误报告 

### ISSUE THREAD

**Issue by hejianmei** [JimmyLv/BibiGPT#90]
您好，我clone了main,想在本地搭建一个
然后执行了 npm run dev
出错了
请问是我的使用方法有问题吗？

```
(base) nandateumenoMacBook-puro:BibiGPT hejianmei$ npm run dev

> bibi-gpt@2.5.0 dev /Users/hejianmei/Desktop/BibiGPT
> next dev

sh: next: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! bibi-gpt@2.5.0 dev: `next dev`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the bibi-gpt@2.5.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hejianmei/.npm/_logs/2023-04-06T14_39_45_971Z-debug.log
(base) nandateumenoMacBook-puro:BibiGPT hejianmei$ 
```

以下是 2023-04-06T14_39_45_971Z-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle bibi-gpt@2.5.0~predev: bibi-gpt@2.5.0
6 info lifecycle bibi-gpt@2.5.0~dev: bibi-gpt@2.5.0
7 verbose lifecycle bibi-gpt@2.5.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle bibi-gpt@2.5.0~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/hejianmei/Desktop/BibiGPT/node_modules/.bin:/Users/hejianmei/.pyenv/shims:/Users/hejianmei/.pyenv/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Users/hejianmei/opt/anaconda3/bin:/Users/hejianmei/opt/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle bibi-gpt@2.5.0~dev: CWD: /Users/hejianmei/Desktop/BibiGPT
10 silly lifecycle bibi-gpt@2.5.0~dev: Args: [ '-c', 'next dev' ]
11 info lifecycle bibi-gpt@2.5.0~dev: Failed to exec dev script
12 verbose stack Error: bibi-gpt@2.5.0 dev: `next dev`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:310:20)
12 verbose stack     at maybeClose (internal/child_process.js:1021:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
13 verbose pkgid bibi-gpt@2.5.0
14 verbose cwd /Users/hejianmei/Desktop/BibiGPT
15 verbose Darwin 21.6.0
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
17 verbose node v12.16.2
18 verbose npm  v6.14.4
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error bibi-gpt@2.5.0 dev: `next dev`
23 error spawn ENOENT
24 error Failed at the bibi-gpt@2.5.0 dev script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by DongHY1** [comment]
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
没有 npm install 安装依赖吗？

**Comment by bbingz** [comment]
没有用的，放弃吧，我昨天也是装完依赖，解决完好几个报错，还剩一个 fs 解决不了。
建议使用chatGPTBox （https://github.com/josStorer/chatGPTBox），一个插件就解决问题了。
